<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="22230" started-at="2017-11-29T06:29:38Z" finished-at="2017-11-29T06:30:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="22230" started-at="2017-11-29T06:29:38Z" finished-at="2017-11-29T06:30:00Z">
      <class name="com.samaya.qa.testcases.organisation.DepartmentpageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.samaya.qa.testcases.organisation.DepartmentpageTest@d25987]" name="setUp" is-config="true" duration-ms="23462" started-at="2017-11-29T11:59:15Z" finished-at="2017-11-29T11:59:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyDepartmentPage()[pri:4, instance:com.samaya.qa.testcases.organisation.DepartmentpageTest@d25987]" name="verifyDepartmentPage" duration-ms="5533" started-at="2017-11-29T11:59:38Z" finished-at="2017-11-29T11:59:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyDepartmentPage -->
        <test-method status="SKIP" signature="validateDepartment(java.lang.String)[pri:5, instance:com.samaya.qa.testcases.organisation.DepartmentpageTest@d25987]" name="validateDepartment" duration-ms="0" started-at="2017-11-29T11:59:44Z" data-provider="getData" finished-at="2017-11-29T11:59:44Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:115)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:509)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1308)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1036)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1126)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException
	at com.samaya.qa.util.TestUtil.getTestData(TestUtil.java:106)
	at com.samaya.qa.testcases.organisation.DepartmentpageTest.getData(DepartmentpageTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:55)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
	... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDepartment -->
        <test-method status="PASS" signature="logoutDepartmentScreen()[pri:6, instance:com.samaya.qa.testcases.organisation.DepartmentpageTest@d25987]" name="logoutDepartmentScreen" duration-ms="2202" started-at="2017-11-29T11:59:44Z" finished-at="2017-11-29T11:59:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutDepartmentScreen -->
        <test-method status="PASS" signature="logout()[pri:0, instance:com.samaya.qa.testcases.organisation.DepartmentpageTest@d25987]" name="logout" is-config="true" duration-ms="13735" started-at="2017-11-29T11:59:47Z" finished-at="2017-11-29T12:00:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- com.samaya.qa.testcases.organisation.DepartmentpageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
